[package]
name = "deep-freeze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
dotenv = "0.15.0"
dropbox-sdk = "0.15.0"
sqlite = "0.31.0"
