name: "Terraform Plan"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      TF_VARS:
        type: string
        description: "Terraform variables"
        required: true
        default: ${{ secrets.TF_VARS }}
      CONFIG_DIRECTORY:
        type: string
        description: "Terraform configuration directory"
        required: true
        default: "./"

env:
  TF_VARS: ${{ secrets.TF_VARS }}
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
